/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.urctf.protocol;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * A team
 */
public enum Team implements org.apache.thrift.TEnum {
  RED(1),
  BLUE(2);

  private final int value;

  private Team(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Team findByValue(int value) { 
    switch (value) {
      case 1:
        return RED;
      case 2:
        return BLUE;
      default:
        return null;
    }
  }
}
